### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by illussystems** [Priximan/Project_ReSurvivor#1]
Have you made any progress with - for example - the shooting/damage?
If the answer is "yes", is there any way to get an updated version of the project? The beginning of this project was awesome, it would be a shame if you canceled it.

**Comment by DamirPorobic** [comment]
Hey ya, unfortunately, we stopped working on this as the both designers that worked with me on the project dropped out due to some other private projects and I lack the design skills to progress any further.
